class Nerd {
  final String title, content, user;

  Nerd(this.title, this.content, this.user);
}

final List<Nerd> nerds = <Nerd>[
  Nerd(
      "flutter is so awesome",
      "The Ethical AI club of Lucas College , in conjunction with IBM D-NA is offering you an exciting opportunity to learn how to build a stellar career in Data science this long vacation! It is opened to students with both IT and non-IT backgrounds. Connect with industry influencers and hear the latest research on the future of the Digital age as you find exciting opportunities in the industry like AI, IoT, and others. *Date:* Monday 17th June  to Friday 21st June, 2019c *Time:* 10am to 4pm each day *To register:* Use this link and fill the appropriate time and venue https://docs.google.com/forms/d/e/1FAIpQLScv-d_9bwjLZRhX1kKkk2S4u7qIurijvUz8LhokT7ZOmKffyw/viewform?vc=0&c=0&w=1 Become part of an incredible network of Ethical AI club and IBM D-NA Bootcampers *Proudly brought to you  by IBM D-NA and LUCAS COLLEGE, ACCRA *",
      "Wilfred"),
  Nerd(
      "flutter is so awesome",
      "The Ethical AI club of Lucas College , in conjunction with IBM D-NA is offering you an exciting opportunity to learn how to build a stellar career in Data science this long vacation! It is opened to students with both IT and non-IT backgrounds. Connect with industry influencers and hear the latest research on the future of the Digital age as you find exciting opportunities in the industry like AI, IoT, and others. *Date:* Monday 17th June  to Friday 21st June, 2019c *Time:* 10am to 4pm each day *To register:* Use this link and fill the appropriate time and venue https://docs.google.com/forms/d/e/1FAIpQLScv-d_9bwjLZRhX1kKkk2S4u7qIurijvUz8LhokT7ZOmKffyw/viewform?vc=0&c=0&w=1 Become part of an incredible network of Ethical AI club and IBM D-NA Bootcampers *Proudly brought to you  by IBM D-NA and LUCAS COLLEGE, ACCRA *",
      "Wilfred"),
  Nerd(
      "flutter is so awesome",
      "The Ethical AI club of Lucas College , in conjunction with IBM D-NA is offering you an exciting opportunity to learn how to build a stellar career in Data science this long vacation! It is opened to students with both IT and non-IT backgrounds. Connect with industry influencers and hear the latest research on the future of the Digital age as you find exciting opportunities in the industry like AI, IoT, and others. *Date:* Monday 17th June  to Friday 21st June, 2019c *Time:* 10am to 4pm each day *To register:* Use this link and fill the appropriate time and venue https://docs.google.com/forms/d/e/1FAIpQLScv-d_9bwjLZRhX1kKkk2S4u7qIurijvUz8LhokT7ZOmKffyw/viewform?vc=0&c=0&w=1 Become part of an incredible network of Ethical AI club and IBM D-NA Bootcampers *Proudly brought to you  by IBM D-NA and LUCAS COLLEGE, ACCRA *",
      "Wilfred"),
  Nerd(
      "flutter is so awesome",
      "The Ethical AI club of Lucas College , in conjunction with IBM D-NA is offering you an exciting opportunity to learn how to build a stellar career in Data science this long vacation! It is opened to students with both IT and non-IT backgrounds. Connect with industry influencers and hear the latest research on the future of the Digital age as you find exciting opportunities in the industry like AI, IoT, and others. *Date:* Monday 17th June  to Friday 21st June, 2019c *Time:* 10am to 4pm each day *To register:* Use this link and fill the appropriate time and venue https://docs.google.com/forms/d/e/1FAIpQLScv-d_9bwjLZRhX1kKkk2S4u7qIurijvUz8LhokT7ZOmKffyw/viewform?vc=0&c=0&w=1 Become part of an incredible network of Ethical AI club and IBM D-NA Bootcampers *Proudly brought to you  by IBM D-NA and LUCAS COLLEGE, ACCRA *",
      "Wilfred"),
  Nerd(
      "flutter is so awesome",
      "The Ethical AI club of Lucas College , in conjunction with IBM D-NA is offering you an exciting opportunity to learn how to build a stellar career in Data science this long vacation! It is opened to students with both IT and non-IT backgrounds. Connect with industry influencers and hear the latest research on the future of the Digital age as you find exciting opportunities in the industry like AI, IoT, and others. *Date:* Monday 17th June  to Friday 21st June, 2019c *Time:* 10am to 4pm each day *To register:* Use this link and fill the appropriate time and venue https://docs.google.com/forms/d/e/1FAIpQLScv-d_9bwjLZRhX1kKkk2S4u7qIurijvUz8LhokT7ZOmKffyw/viewform?vc=0&c=0&w=1 Become part of an incredible network of Ethical AI club and IBM D-NA Bootcampers *Proudly brought to you  by IBM D-NA and LUCAS COLLEGE, ACCRA *",
      "Wilfred"),
  Nerd(
      "flutter is so awesome",
      "The Ethical AI club of Lucas College , in conjunction with IBM D-NA is offering you an exciting opportunity to learn how to build a stellar career in Data science this long vacation! It is opened to students with both IT and non-IT backgrounds. Connect with industry influencers and hear the latest research on the future of the Digital age as you find exciting opportunities in the industry like AI, IoT, and others. *Date:* Monday 17th June  to Friday 21st June, 2019c *Time:* 10am to 4pm each day *To register:* Use this link and fill the appropriate time and venue https://docs.google.com/forms/d/e/1FAIpQLScv-d_9bwjLZRhX1kKkk2S4u7qIurijvUz8LhokT7ZOmKffyw/viewform?vc=0&c=0&w=1 Become part of an incredible network of Ethical AI club and IBM D-NA Bootcampers *Proudly brought to you  by IBM D-NA and LUCAS COLLEGE, ACCRA *",
      "Wilfred"),
  Nerd(
      "flutter is so awesome",
      "The Ethical AI club of Lucas College , in conjunction with IBM D-NA is offering you an exciting opportunity to learn how to build a stellar career in Data science this long vacation! It is opened to students with both IT and non-IT backgrounds. Connect with industry influencers and hear the latest research on the future of the Digital age as you find exciting opportunities in the industry like AI, IoT, and others. *Date:* Monday 17th June  to Friday 21st June, 2019c *Time:* 10am to 4pm each day *To register:* Use this link and fill the appropriate time and venue https://docs.google.com/forms/d/e/1FAIpQLScv-d_9bwjLZRhX1kKkk2S4u7qIurijvUz8LhokT7ZOmKffyw/viewform?vc=0&c=0&w=1 Become part of an incredible network of Ethical AI club and IBM D-NA Bootcampers *Proudly brought to you  by IBM D-NA and LUCAS COLLEGE, ACCRA *",
      "Wilfred"),
  Nerd(
      "flutter is so awesome",
      "The Ethical AI club of Lucas College , in conjunction with IBM D-NA is offering you an exciting opportunity to learn how to build a stellar career in Data science this long vacation! It is opened to students with both IT and non-IT backgrounds. Connect with industry influencers and hear the latest research on the future of the Digital age as you find exciting opportunities in the industry like AI, IoT, and others. *Date:* Monday 17th June  to Friday 21st June, 2019c *Time:* 10am to 4pm each day *To register:* Use this link and fill the appropriate time and venue https://docs.google.com/forms/d/e/1FAIpQLScv-d_9bwjLZRhX1kKkk2S4u7qIurijvUz8LhokT7ZOmKffyw/viewform?vc=0&c=0&w=1 Become part of an incredible network of Ethical AI club and IBM D-NA Bootcampers *Proudly brought to you  by IBM D-NA and LUCAS COLLEGE, ACCRA *",
      "Wilfred"),
  Nerd(
      "flutter is so awesome",
      "The Ethical AI club of Lucas College , in conjunction with IBM D-NA is offering you an exciting opportunity to learn how to build a stellar career in Data science this long vacation! It is opened to students with both IT and non-IT backgrounds. Connect with industry influencers and hear the latest research on the future of the Digital age as you find exciting opportunities in the industry like AI, IoT, and others. *Date:* Monday 17th June  to Friday 21st June, 2019c *Time:* 10am to 4pm each day *To register:* Use this link and fill the appropriate time and venue https://docs.google.com/forms/d/e/1FAIpQLScv-d_9bwjLZRhX1kKkk2S4u7qIurijvUz8LhokT7ZOmKffyw/viewform?vc=0&c=0&w=1 Become part of an incredible network of Ethical AI club and IBM D-NA Bootcampers *Proudly brought to you  by IBM D-NA and LUCAS COLLEGE, ACCRA *",
      "Wilfred"),
  Nerd(
      "flutter is so awesome",
      "The Ethical AI club of Lucas College , in conjunction with IBM D-NA is offering you an exciting opportunity to learn how to build a stellar career in Data science this long vacation! It is opened to students with both IT and non-IT backgrounds. Connect with industry influencers and hear the latest research on the future of the Digital age as you find exciting opportunities in the industry like AI, IoT, and others. *Date:* Monday 17th June  to Friday 21st June, 2019c *Time:* 10am to 4pm each day *To register:* Use this link and fill the appropriate time and venue https://docs.google.com/forms/d/e/1FAIpQLScv-d_9bwjLZRhX1kKkk2S4u7qIurijvUz8LhokT7ZOmKffyw/viewform?vc=0&c=0&w=1 Become part of an incredible network of Ethical AI club and IBM D-NA Bootcampers *Proudly brought to you  by IBM D-NA and LUCAS COLLEGE, ACCRA *",
      "Wilfred"),
  Nerd(
      "flutter is so awesome",
      "The Ethical AI club of Lucas College , in conjunction with IBM D-NA is offering you an exciting opportunity to learn how to build a stellar career in Data science this long vacation! It is opened to students with both IT and non-IT backgrounds. Connect with industry influencers and hear the latest research on the future of the Digital age as you find exciting opportunities in the industry like AI, IoT, and others. *Date:* Monday 17th June  to Friday 21st June, 2019c *Time:* 10am to 4pm each day *To register:* Use this link and fill the appropriate time and venue https://docs.google.com/forms/d/e/1FAIpQLScv-d_9bwjLZRhX1kKkk2S4u7qIurijvUz8LhokT7ZOmKffyw/viewform?vc=0&c=0&w=1 Become part of an incredible network of Ethical AI club and IBM D-NA Bootcampers *Proudly brought to you  by IBM D-NA and LUCAS COLLEGE, ACCRA *",
      "Wilfred"),
  Nerd(
      "flutter is so awesome",
      "The Ethical AI club of Lucas College , in conjunction with IBM D-NA is offering you an exciting opportunity to learn how to build a stellar career in Data science this long vacation! It is opened to students with both IT and non-IT backgrounds. Connect with industry influencers and hear the latest research on the future of the Digital age as you find exciting opportunities in the industry like AI, IoT, and others. *Date:* Monday 17th June  to Friday 21st June, 2019c *Time:* 10am to 4pm each day *To register:* Use this link and fill the appropriate time and venue https://docs.google.com/forms/d/e/1FAIpQLScv-d_9bwjLZRhX1kKkk2S4u7qIurijvUz8LhokT7ZOmKffyw/viewform?vc=0&c=0&w=1 Become part of an incredible network of Ethical AI club and IBM D-NA Bootcampers *Proudly brought to you  by IBM D-NA and LUCAS COLLEGE, ACCRA *",
      "Wilfred"),
  Nerd(
      "flutter is so awesome",
      "The Ethical AI club of Lucas College , in conjunction with IBM D-NA is offering you an exciting opportunity to learn how to build a stellar career in Data science this long vacation! It is opened to students with both IT and non-IT backgrounds. Connect with industry influencers and hear the latest research on the future of the Digital age as you find exciting opportunities in the industry like AI, IoT, and others. *Date:* Monday 17th June  to Friday 21st June, 2019c *Time:* 10am to 4pm each day *To register:* Use this link and fill the appropriate time and venue https://docs.google.com/forms/d/e/1FAIpQLScv-d_9bwjLZRhX1kKkk2S4u7qIurijvUz8LhokT7ZOmKffyw/viewform?vc=0&c=0&w=1 Become part of an incredible network of Ethical AI club and IBM D-NA Bootcampers *Proudly brought to you  by IBM D-NA and LUCAS COLLEGE, ACCRA *",
      "Wilfred"),
  Nerd(
      "flutter is so awesome",
      "The Ethical AI club of Lucas College , in conjunction with IBM D-NA is offering you an exciting opportunity to learn how to build a stellar career in Data science this long vacation! It is opened to students with both IT and non-IT backgrounds. Connect with industry influencers and hear the latest research on the future of the Digital age as you find exciting opportunities in the industry like AI, IoT, and others. *Date:* Monday 17th June  to Friday 21st June, 2019c *Time:* 10am to 4pm each day *To register:* Use this link and fill the appropriate time and venue https://docs.google.com/forms/d/e/1FAIpQLScv-d_9bwjLZRhX1kKkk2S4u7qIurijvUz8LhokT7ZOmKffyw/viewform?vc=0&c=0&w=1 Become part of an incredible network of Ethical AI club and IBM D-NA Bootcampers *Proudly brought to you  by IBM D-NA and LUCAS COLLEGE, ACCRA *",
      "Wilfred"),
  Nerd(
      "flutter is so awesome",
      "The Ethical AI club of Lucas College , in conjunction with IBM D-NA is offering you an exciting opportunity to learn how to build a stellar career in Data science this long vacation! It is opened to students with both IT and non-IT backgrounds. Connect with industry influencers and hear the latest research on the future of the Digital age as you find exciting opportunities in the industry like AI, IoT, and others. *Date:* Monday 17th June  to Friday 21st June, 2019c *Time:* 10am to 4pm each day *To register:* Use this link and fill the appropriate time and venue https://docs.google.com/forms/d/e/1FAIpQLScv-d_9bwjLZRhX1kKkk2S4u7qIurijvUz8LhokT7ZOmKffyw/viewform?vc=0&c=0&w=1 Become part of an incredible network of Ethical AI club and IBM D-NA Bootcampers *Proudly brought to you  by IBM D-NA and LUCAS COLLEGE, ACCRA *",
      "Wilfred"),
  Nerd(
      "flutter is so awesome",
      "The Ethical AI club of Lucas College , in conjunction with IBM D-NA is offering you an exciting opportunity to learn how to build a stellar career in Data science this long vacation! It is opened to students with both IT and non-IT backgrounds. Connect with industry influencers and hear the latest research on the future of the Digital age as you find exciting opportunities in the industry like AI, IoT, and others. *Date:* Monday 17th June  to Friday 21st June, 2019c *Time:* 10am to 4pm each day *To register:* Use this link and fill the appropriate time and venue https://docs.google.com/forms/d/e/1FAIpQLScv-d_9bwjLZRhX1kKkk2S4u7qIurijvUz8LhokT7ZOmKffyw/viewform?vc=0&c=0&w=1 Become part of an incredible network of Ethical AI club and IBM D-NA Bootcampers *Proudly brought to you  by IBM D-NA and LUCAS COLLEGE, ACCRA *",
      "Wilfred"),
  Nerd(
      "flutter is so awesome",
      "The Ethical AI club of Lucas College , in conjunction with IBM D-NA is offering you an exciting opportunity to learn how to build a stellar career in Data science this long vacation! It is opened to students with both IT and non-IT backgrounds. Connect with industry influencers and hear the latest research on the future of the Digital age as you find exciting opportunities in the industry like AI, IoT, and others. *Date:* Monday 17th June  to Friday 21st June, 2019c *Time:* 10am to 4pm each day *To register:* Use this link and fill the appropriate time and venue https://docs.google.com/forms/d/e/1FAIpQLScv-d_9bwjLZRhX1kKkk2S4u7qIurijvUz8LhokT7ZOmKffyw/viewform?vc=0&c=0&w=1 Become part of an incredible network of Ethical AI club and IBM D-NA Bootcampers *Proudly brought to you  by IBM D-NA and LUCAS COLLEGE, ACCRA *",
      "Wilfred"),
  Nerd(
      "flutter is so awesome",
      "The Ethical AI club of Lucas College , in conjunction with IBM D-NA is offering you an exciting opportunity to learn how to build a stellar career in Data science this long vacation! It is opened to students with both IT and non-IT backgrounds. Connect with industry influencers and hear the latest research on the future of the Digital age as you find exciting opportunities in the industry like AI, IoT, and others. *Date:* Monday 17th June  to Friday 21st June, 2019c *Time:* 10am to 4pm each day *To register:* Use this link and fill the appropriate time and venue https://docs.google.com/forms/d/e/1FAIpQLScv-d_9bwjLZRhX1kKkk2S4u7qIurijvUz8LhokT7ZOmKffyw/viewform?vc=0&c=0&w=1 Become part of an incredible network of Ethical AI club and IBM D-NA Bootcampers *Proudly brought to you  by IBM D-NA and LUCAS COLLEGE, ACCRA *",
      "Wilfred"),
  Nerd(
      "flutter is so awesome",
      "The Ethical AI club of Lucas College , in conjunction with IBM D-NA is offering you an exciting opportunity to learn how to build a stellar career in Data science this long vacation! It is opened to students with both IT and non-IT backgrounds. Connect with industry influencers and hear the latest research on the future of the Digital age as you find exciting opportunities in the industry like AI, IoT, and others. *Date:* Monday 17th June  to Friday 21st June, 2019c *Time:* 10am to 4pm each day *To register:* Use this link and fill the appropriate time and venue https://docs.google.com/forms/d/e/1FAIpQLScv-d_9bwjLZRhX1kKkk2S4u7qIurijvUz8LhokT7ZOmKffyw/viewform?vc=0&c=0&w=1 Become part of an incredible network of Ethical AI club and IBM D-NA Bootcampers *Proudly brought to you  by IBM D-NA and LUCAS COLLEGE, ACCRA *",
      "Wilfred"),
  Nerd(
      "flutter is so awesome",
      "The Ethical AI club of Lucas College , in conjunction with IBM D-NA is offering you an exciting opportunity to learn how to build a stellar career in Data science this long vacation! It is opened to students with both IT and non-IT backgrounds. Connect with industry influencers and hear the latest research on the future of the Digital age as you find exciting opportunities in the industry like AI, IoT, and others. *Date:* Monday 17th June  to Friday 21st June, 2019c *Time:* 10am to 4pm each day *To register:* Use this link and fill the appropriate time and venue https://docs.google.com/forms/d/e/1FAIpQLScv-d_9bwjLZRhX1kKkk2S4u7qIurijvUz8LhokT7ZOmKffyw/viewform?vc=0&c=0&w=1 Become part of an incredible network of Ethical AI club and IBM D-NA Bootcampers *Proudly brought to you  by IBM D-NA and LUCAS COLLEGE, ACCRA *",
      "Wilfred"),
  Nerd(
      "flutter is so awesome",
      "The Ethical AI club of Lucas College , in conjunction with IBM D-NA is offering you an exciting opportunity to learn how to build a stellar career in Data science this long vacation! It is opened to students with both IT and non-IT backgrounds. Connect with industry influencers and hear the latest research on the future of the Digital age as you find exciting opportunities in the industry like AI, IoT, and others. *Date:* Monday 17th June  to Friday 21st June, 2019c *Time:* 10am to 4pm each day *To register:* Use this link and fill the appropriate time and venue https://docs.google.com/forms/d/e/1FAIpQLScv-d_9bwjLZRhX1kKkk2S4u7qIurijvUz8LhokT7ZOmKffyw/viewform?vc=0&c=0&w=1 Become part of an incredible network of Ethical AI club and IBM D-NA Bootcampers *Proudly brought to you  by IBM D-NA and LUCAS COLLEGE, ACCRA *",
      "Wilfred"),
  Nerd(
      "flutter is so awesome",
      "The Ethical AI club of Lucas College , in conjunction with IBM D-NA is offering you an exciting opportunity to learn how to build a stellar career in Data science this long vacation! It is opened to students with both IT and non-IT backgrounds. Connect with industry influencers and hear the latest research on the future of the Digital age as you find exciting opportunities in the industry like AI, IoT, and others. *Date:* Monday 17th June  to Friday 21st June, 2019c *Time:* 10am to 4pm each day *To register:* Use this link and fill the appropriate time and venue https://docs.google.com/forms/d/e/1FAIpQLScv-d_9bwjLZRhX1kKkk2S4u7qIurijvUz8LhokT7ZOmKffyw/viewform?vc=0&c=0&w=1 Become part of an incredible network of Ethical AI club and IBM D-NA Bootcampers *Proudly brought to you  by IBM D-NA and LUCAS COLLEGE, ACCRA *",
      "Wilfred"),
  Nerd(
      "flutter is so awesome",
      "The Ethical AI club of Lucas College , in conjunction with IBM D-NA is offering you an exciting opportunity to learn how to build a stellar career in Data science this long vacation! It is opened to students with both IT and non-IT backgrounds. Connect with industry influencers and hear the latest research on the future of the Digital age as you find exciting opportunities in the industry like AI, IoT, and others. *Date:* Monday 17th June  to Friday 21st June, 2019c *Time:* 10am to 4pm each day *To register:* Use this link and fill the appropriate time and venue https://docs.google.com/forms/d/e/1FAIpQLScv-d_9bwjLZRhX1kKkk2S4u7qIurijvUz8LhokT7ZOmKffyw/viewform?vc=0&c=0&w=1 Become part of an incredible network of Ethical AI club and IBM D-NA Bootcampers *Proudly brought to you  by IBM D-NA and LUCAS COLLEGE, ACCRA *",
      "Wilfred"),
  Nerd(
      "flutter is so awesome",
      "The Ethical AI club of Lucas College , in conjunction with IBM D-NA is offering you an exciting opportunity to learn how to build a stellar career in Data science this long vacation! It is opened to students with both IT and non-IT backgrounds. Connect with industry influencers and hear the latest research on the future of the Digital age as you find exciting opportunities in the industry like AI, IoT, and others. *Date:* Monday 17th June  to Friday 21st June, 2019c *Time:* 10am to 4pm each day *To register:* Use this link and fill the appropriate time and venue https://docs.google.com/forms/d/e/1FAIpQLScv-d_9bwjLZRhX1kKkk2S4u7qIurijvUz8LhokT7ZOmKffyw/viewform?vc=0&c=0&w=1 Become part of an incredible network of Ethical AI club and IBM D-NA Bootcampers *Proudly brought to you  by IBM D-NA and LUCAS COLLEGE, ACCRA *",
      "Wilfred"),
  Nerd(
      "flutter is so awesome",
      "The Ethical AI club of Lucas College , in conjunction with IBM D-NA is offering you an exciting opportunity to learn how to build a stellar career in Data science this long vacation! It is opened to students with both IT and non-IT backgrounds. Connect with industry influencers and hear the latest research on the future of the Digital age as you find exciting opportunities in the industry like AI, IoT, and others. *Date:* Monday 17th June  to Friday 21st June, 2019c *Time:* 10am to 4pm each day *To register:* Use this link and fill the appropriate time and venue https://docs.google.com/forms/d/e/1FAIpQLScv-d_9bwjLZRhX1kKkk2S4u7qIurijvUz8LhokT7ZOmKffyw/viewform?vc=0&c=0&w=1 Become part of an incredible network of Ethical AI club and IBM D-NA Bootcampers *Proudly brought to you  by IBM D-NA and LUCAS COLLEGE, ACCRA *",
      "Wilfred"),
  Nerd(
      "flutter is so awesome",
      "The Ethical AI club of Lucas College , in conjunction with IBM D-NA is offering you an exciting opportunity to learn how to build a stellar career in Data science this long vacation! It is opened to students with both IT and non-IT backgrounds. Connect with industry influencers and hear the latest research on the future of the Digital age as you find exciting opportunities in the industry like AI, IoT, and others. *Date:* Monday 17th June  to Friday 21st June, 2019c *Time:* 10am to 4pm each day *To register:* Use this link and fill the appropriate time and venue https://docs.google.com/forms/d/e/1FAIpQLScv-d_9bwjLZRhX1kKkk2S4u7qIurijvUz8LhokT7ZOmKffyw/viewform?vc=0&c=0&w=1 Become part of an incredible network of Ethical AI club and IBM D-NA Bootcampers *Proudly brought to you  by IBM D-NA and LUCAS COLLEGE, ACCRA *",
      "Wilfred"),
  Nerd(
      "flutter is so awesome",
      "The Ethical AI club of Lucas College , in conjunction with IBM D-NA is offering you an exciting opportunity to learn how to build a stellar career in Data science this long vacation! It is opened to students with both IT and non-IT backgrounds. Connect with industry influencers and hear the latest research on the future of the Digital age as you find exciting opportunities in the industry like AI, IoT, and others. *Date:* Monday 17th June  to Friday 21st June, 2019c *Time:* 10am to 4pm each day *To register:* Use this link and fill the appropriate time and venue https://docs.google.com/forms/d/e/1FAIpQLScv-d_9bwjLZRhX1kKkk2S4u7qIurijvUz8LhokT7ZOmKffyw/viewform?vc=0&c=0&w=1 Become part of an incredible network of Ethical AI club and IBM D-NA Bootcampers *Proudly brought to you  by IBM D-NA and LUCAS COLLEGE, ACCRA *",
      "Wilfred"),
  Nerd(
      "flutter is so awesome",
      "The Ethical AI club of Lucas College , in conjunction with IBM D-NA is offering you an exciting opportunity to learn how to build a stellar career in Data science this long vacation! It is opened to students with both IT and non-IT backgrounds. Connect with industry influencers and hear the latest research on the future of the Digital age as you find exciting opportunities in the industry like AI, IoT, and others. *Date:* Monday 17th June  to Friday 21st June, 2019c *Time:* 10am to 4pm each day *To register:* Use this link and fill the appropriate time and venue https://docs.google.com/forms/d/e/1FAIpQLScv-d_9bwjLZRhX1kKkk2S4u7qIurijvUz8LhokT7ZOmKffyw/viewform?vc=0&c=0&w=1 Become part of an incredible network of Ethical AI club and IBM D-NA Bootcampers *Proudly brought to you  by IBM D-NA and LUCAS COLLEGE, ACCRA *",
      "Wilfred"),
  Nerd(
      "flutter is so awesome",
      "The Ethical AI club of Lucas College , in conjunction with IBM D-NA is offering you an exciting opportunity to learn how to build a stellar career in Data science this long vacation! It is opened to students with both IT and non-IT backgrounds. Connect with industry influencers and hear the latest research on the future of the Digital age as you find exciting opportunities in the industry like AI, IoT, and others. *Date:* Monday 17th June  to Friday 21st June, 2019c *Time:* 10am to 4pm each day *To register:* Use this link and fill the appropriate time and venue https://docs.google.com/forms/d/e/1FAIpQLScv-d_9bwjLZRhX1kKkk2S4u7qIurijvUz8LhokT7ZOmKffyw/viewform?vc=0&c=0&w=1 Become part of an incredible network of Ethical AI club and IBM D-NA Bootcampers *Proudly brought to you  by IBM D-NA and LUCAS COLLEGE, ACCRA *",
      "Wilfred"),
  Nerd(
      "flutter is so awesome",
      "The Ethical AI club of Lucas College , in conjunction with IBM D-NA is offering you an exciting opportunity to learn how to build a stellar career in Data science this long vacation! It is opened to students with both IT and non-IT backgrounds. Connect with industry influencers and hear the latest research on the future of the Digital age as you find exciting opportunities in the industry like AI, IoT, and others. *Date:* Monday 17th June  to Friday 21st June, 2019c *Time:* 10am to 4pm each day *To register:* Use this link and fill the appropriate time and venue https://docs.google.com/forms/d/e/1FAIpQLScv-d_9bwjLZRhX1kKkk2S4u7qIurijvUz8LhokT7ZOmKffyw/viewform?vc=0&c=0&w=1 Become part of an incredible network of Ethical AI club and IBM D-NA Bootcampers *Proudly brought to you  by IBM D-NA and LUCAS COLLEGE, ACCRA *",
      "Wilfred"),
  Nerd(
      "flutter is so awesome",
      "The Ethical AI club of Lucas College , in conjunction with IBM D-NA is offering you an exciting opportunity to learn how to build a stellar career in Data science this long vacation! It is opened to students with both IT and non-IT backgrounds. Connect with industry influencers and hear the latest research on the future of the Digital age as you find exciting opportunities in the industry like AI, IoT, and others. *Date:* Monday 17th June  to Friday 21st June, 2019c *Time:* 10am to 4pm each day *To register:* Use this link and fill the appropriate time and venue https://docs.google.com/forms/d/e/1FAIpQLScv-d_9bwjLZRhX1kKkk2S4u7qIurijvUz8LhokT7ZOmKffyw/viewform?vc=0&c=0&w=1 Become part of an incredible network of Ethical AI club and IBM D-NA Bootcampers *Proudly brought to you  by IBM D-NA and LUCAS COLLEGE, ACCRA *",
      "Wilfred"),
  Nerd(
      "flutter is so awesome",
      "The Ethical AI club of Lucas College , in conjunction with IBM D-NA is offering you an exciting opportunity to learn how to build a stellar career in Data science this long vacation! It is opened to students with both IT and non-IT backgrounds. Connect with industry influencers and hear the latest research on the future of the Digital age as you find exciting opportunities in the industry like AI, IoT, and others. *Date:* Monday 17th June  to Friday 21st June, 2019c *Time:* 10am to 4pm each day *To register:* Use this link and fill the appropriate time and venue https://docs.google.com/forms/d/e/1FAIpQLScv-d_9bwjLZRhX1kKkk2S4u7qIurijvUz8LhokT7ZOmKffyw/viewform?vc=0&c=0&w=1 Become part of an incredible network of Ethical AI club and IBM D-NA Bootcampers *Proudly brought to you  by IBM D-NA and LUCAS COLLEGE, ACCRA *",
      "Wilfred"),
];
